## Numpy


### Arrays

In [1]:
import numpy as np

In [4]:
## Create a rank 1 array
a = np.array([1,2,3])

print(type(a))


<class 'numpy.ndarray'>
(3,)


In [5]:
## print the shape of an array
print(a.shape)

(3,)


In [6]:
## accessing element of an array
print(a[0], a[1], a[2])

1 2 3


In [7]:
## changing the elements of an array
a[0] = 5

print(a)

[5 2 3]


In [10]:
## create a rank 2 array
b = np.array([[1,2,3],[4,5,6]])

print(b.shape)

(2, 3)


In [11]:
## print element of the array
print(b[0,0], b[0,1], b[1,0])

1 2 4


Numpy functions to create arrays

In [13]:
import numpy as np

## create an array of all zeros
a = np.zeros((2,2))
print(a)


[[0. 0.]
 [0. 0.]]


In [14]:
## create an array of all ones
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [15]:
## create a constant array
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [16]:
## Create a 2x2 identify matrix
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [17]:
## Create an array filled with random values
e = np.random.random((2,2))
print(e)

[[0.92878079 0.23628472]
 [0.38517033 0.97688963]]


### Array indexing


In [20]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
## print the shape
print(a.shape)

(3, 4)


In [22]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]
